language: node_js
node_js:
  - "7"

before_install:
  - git config --global push.default matching
  - git config --global user.name "lml2014" 
  - git config --global user.email "982905676@qq.com"

install:
  - npm install hexo-cli -g
  - npm install hexo --save
  - npm install
  # - npm install hexo-generator-feed --save
  - npm install hexo-deployer-git --save
  # - npm install hexo-renderer-ejs --save
  # - npm install hexo-renderer-stylus --save
  # - npm install hexo-renderer-marked --save
  # - npm install hexo-renderer-sass --save

script:
  - hexo clean
  - hexo generate

after_success:
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --quiet --force https://github.com/lml2014/lml2014.github.io.git master

branches:
  only:
    - hexo
cache:
  directories:
    - node_modules